// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/catalog/pb (interfaces: CatalogServiceServer)
//
// Generated by this command:
//
// 	mockgen -destination=order/catalog_server_mock.go -package=order github.com/RathodViraj/go-microservice-graphql-grpc/catalog/pb CatalogServiceServer
//

package order

import (
	"context"
	"reflect"

	catalogpb "github.com/RathodViraj/go-microservice-graphql-grpc/catalog/pb"
	"go.uber.org/mock/gomock"
)

// MockCatalogServiceServer is a mock of CatalogServiceServer interface.
type MockCatalogServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceServerMockRecorder
	catalogpb.UnimplementedCatalogServiceServer
}

// MockCatalogServiceServerMockRecorder is the mock recorder for MockCatalogServiceServer.
type MockCatalogServiceServerMockRecorder struct {
	mock *MockCatalogServiceServer
}

// NewMockCatalogServiceServer creates a new mock instance.
func NewMockCatalogServiceServer(ctrl *gomock.Controller) *MockCatalogServiceServer {
	mock := &MockCatalogServiceServer{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceServer) EXPECT() *MockCatalogServiceServerMockRecorder {
	return m.recorder
}

// GetProducts mocks base method.
func (m *MockCatalogServiceServer) GetProducts(ctx context.Context, req *catalogpb.GetProductsRequest) (*catalogpb.GetProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx, req)
	ret0, _ := ret[0].(*catalogpb.GetProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockCatalogServiceServerMockRecorder) GetProducts(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockCatalogServiceServer)(nil).GetProducts), ctx, req)
}
