// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/order (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=order/repository_mock.go -package=order github.com/RathodViraj/go-microservice-graphql-grpc/order Repository
//

// Package order is a generated GoMock package.
package order

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
}

// GetOrderForAccount mocks base method.
func (m *MockRepository) GetOrderForAccount(ctx context.Context, accountID string) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderForAccount", ctx, accountID)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderForAccount indicates an expected call of GetOrderForAccount.
func (mr *MockRepositoryMockRecorder) GetOrderForAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderForAccount", reflect.TypeOf((*MockRepository)(nil).GetOrderForAccount), ctx, accountID)
}

// PutOrder mocks base method.
func (m *MockRepository) PutOrder(ctx context.Context, o Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutOrder", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutOrder indicates an expected call of PutOrder.
func (mr *MockRepositoryMockRecorder) PutOrder(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutOrder", reflect.TypeOf((*MockRepository)(nil).PutOrder), ctx, o)
}
