// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/order/pb (interfaces: OrderServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=order/server_mock.go -package=order github.com/RathodViraj/go-microservice-graphql-grpc/order/pb OrderServiceClient
//

// Package order is a generated GoMock package.
package order

import (
	context "context"
	reflect "reflect"

	pb "github.com/RathodViraj/go-microservice-graphql-grpc/order/pb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderServiceClient is a mock of OrderServiceClient interface.
type MockOrderServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceClientMockRecorder
	isgomock struct{}
}

// MockOrderServiceClientMockRecorder is the mock recorder for MockOrderServiceClient.
type MockOrderServiceClientMockRecorder struct {
	mock *MockOrderServiceClient
}

// NewMockOrderServiceClient creates a new mock instance.
func NewMockOrderServiceClient(ctrl *gomock.Controller) *MockOrderServiceClient {
	mock := &MockOrderServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrderServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceClient) EXPECT() *MockOrderServiceClientMockRecorder {
	return m.recorder
}

// GetOrdersForAccount mocks base method.
func (m *MockOrderServiceClient) GetOrdersForAccount(ctx context.Context, in *pb.GetOrdersForAccountRequest, opts ...grpc.CallOption) (*pb.GetOrdersForAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrdersForAccount", varargs...)
	ret0, _ := ret[0].(*pb.GetOrdersForAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForAccount indicates an expected call of GetOrdersForAccount.
func (mr *MockOrderServiceClientMockRecorder) GetOrdersForAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForAccount", reflect.TypeOf((*MockOrderServiceClient)(nil).GetOrdersForAccount), varargs...)
}

// PostOrder mocks base method.
func (m *MockOrderServiceClient) PostOrder(ctx context.Context, in *pb.PostOrderRequest, opts ...grpc.CallOption) (*pb.PostOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostOrder", varargs...)
	ret0, _ := ret[0].(*pb.PostOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOrder indicates an expected call of PostOrder.
func (mr *MockOrderServiceClientMockRecorder) PostOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).PostOrder), varargs...)
}
