// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/order (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=order/service_mock.go -package=order github.com/RathodViraj/go-microservice-graphql-grpc/order Service
//

// Package order is a generated GoMock package.
package order

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetOrderForAccount mocks base method.
func (m *MockService) GetOrderForAccount(ctx context.Context, accountID string) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderForAccount", ctx, accountID)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderForAccount indicates an expected call of GetOrderForAccount.
func (mr *MockServiceMockRecorder) GetOrderForAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderForAccount", reflect.TypeOf((*MockService)(nil).GetOrderForAccount), ctx, accountID)
}

// PostOrder mocks base method.
func (m *MockService) PostOrder(ctx context.Context, accountID string, products []OrderedProduct) (*Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostOrder", ctx, accountID, products)
	ret0, _ := ret[0].(*Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOrder indicates an expected call of PostOrder.
func (mr *MockServiceMockRecorder) PostOrder(ctx, accountID, products any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOrder", reflect.TypeOf((*MockService)(nil).PostOrder), ctx, accountID, products)
}
