// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/catalog (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=catalog/repository_mock_test.go -package=catalog github.com/RathodViraj/go-microservice-graphql-grpc/catalog Repository
//

// Package catalog is a generated GoMock package.
package catalog

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
}

// GetProductByID mocks base method.
func (m *MockRepository) GetProductByID(ctx context.Context, id string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockRepositoryMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockRepository)(nil).GetProductByID), ctx, id)
}

// ListProducts mocks base method.
func (m *MockRepository) ListProducts(ctx context.Context, skip, take uint64) ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, skip, take)
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockRepositoryMockRecorder) ListProducts(ctx, skip, take any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockRepository)(nil).ListProducts), ctx, skip, take)
}

// ListProductsWithIDs mocks base method.
func (m *MockRepository) ListProductsWithIDs(ctx context.Context, ids []string) ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsWithIDs", ctx, ids)
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsWithIDs indicates an expected call of ListProductsWithIDs.
func (mr *MockRepositoryMockRecorder) ListProductsWithIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsWithIDs", reflect.TypeOf((*MockRepository)(nil).ListProductsWithIDs), ctx, ids)
}

// PutProduct mocks base method.
func (m *MockRepository) PutProduct(ctx context.Context, p Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutProduct", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutProduct indicates an expected call of PutProduct.
func (mr *MockRepositoryMockRecorder) PutProduct(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutProduct", reflect.TypeOf((*MockRepository)(nil).PutProduct), ctx, p)
}

// SearchProducts mocks base method.
func (m *MockRepository) SearchProducts(ctx context.Context, query string, skip, take uint64) ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", ctx, query, skip, take)
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockRepositoryMockRecorder) SearchProducts(ctx, query, skip, take any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockRepository)(nil).SearchProducts), ctx, query, skip, take)
}
