// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/catalog (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=catalog/service_mock_test.go -package=catalog github.com/RathodViraj/go-microservice-graphql-grpc/catalog Service
//

// Package catalog is a generated GoMock package.
package catalog

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetProduct mocks base method.
func (m *MockService) GetProduct(ctx context.Context, id string) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockServiceMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockService)(nil).GetProduct), ctx, id)
}

// GetProducts mocks base method.
func (m *MockService) GetProducts(ctx context.Context, skip, take uint64) ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx, skip, take)
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockServiceMockRecorder) GetProducts(ctx, skip, take any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockService)(nil).GetProducts), ctx, skip, take)
}

// GetProductsById mocks base method.
func (m *MockService) GetProductsById(ctx context.Context, ids []string) ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsById", ctx, ids)
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsById indicates an expected call of GetProductsById.
func (mr *MockServiceMockRecorder) GetProductsById(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsById", reflect.TypeOf((*MockService)(nil).GetProductsById), ctx, ids)
}

// PostProduct mocks base method.
func (m *MockService) PostProduct(ctx context.Context, name, description string, price float64) (*Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostProduct", ctx, name, description, price)
	ret0, _ := ret[0].(*Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostProduct indicates an expected call of PostProduct.
func (mr *MockServiceMockRecorder) PostProduct(ctx, name, description, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostProduct", reflect.TypeOf((*MockService)(nil).PostProduct), ctx, name, description, price)
}

// SearchProduct mocks base method.
func (m *MockService) SearchProduct(ctx context.Context, query string, skip, take uint64) ([]Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProduct", ctx, query, skip, take)
	ret0, _ := ret[0].([]Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProduct indicates an expected call of SearchProduct.
func (mr *MockServiceMockRecorder) SearchProduct(ctx, query, skip, take any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProduct", reflect.TypeOf((*MockService)(nil).SearchProduct), ctx, query, skip, take)
}
