// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RathodViraj/go-microservice-graphql-grpc/catalog/pb (interfaces: CatalogServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=catalog/server_mock_test.go -package=catalog github.com/RathodViraj/go-microservice-graphql-grpc/catalog/pb CatalogServiceClient
//

// Package catalog is a generated GoMock package.
package catalog

import (
	context "context"
	reflect "reflect"

	pb "github.com/RathodViraj/go-microservice-graphql-grpc/catalog/pb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCatalogServiceClient is a mock of CatalogServiceClient interface.
type MockCatalogServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceClientMockRecorder
	isgomock struct{}
}

// MockCatalogServiceClientMockRecorder is the mock recorder for MockCatalogServiceClient.
type MockCatalogServiceClientMockRecorder struct {
	mock *MockCatalogServiceClient
}

// NewMockCatalogServiceClient creates a new mock instance.
func NewMockCatalogServiceClient(ctrl *gomock.Controller) *MockCatalogServiceClient {
	mock := &MockCatalogServiceClient{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceClient) EXPECT() *MockCatalogServiceClientMockRecorder {
	return m.recorder
}

// GetProduct mocks base method.
func (m *MockCatalogServiceClient) GetProduct(ctx context.Context, in *pb.GetProductRequest, opts ...grpc.CallOption) (*pb.GetProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProduct", varargs...)
	ret0, _ := ret[0].(*pb.GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockCatalogServiceClientMockRecorder) GetProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetProduct), varargs...)
}

// GetProducts mocks base method.
func (m *MockCatalogServiceClient) GetProducts(ctx context.Context, in *pb.GetProductsRequest, opts ...grpc.CallOption) (*pb.GetProductsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProducts", varargs...)
	ret0, _ := ret[0].(*pb.GetProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockCatalogServiceClientMockRecorder) GetProducts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetProducts), varargs...)
}

// PostProduct mocks base method.
func (m *MockCatalogServiceClient) PostProduct(ctx context.Context, in *pb.PostProductRequest, opts ...grpc.CallOption) (*pb.PostProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostProduct", varargs...)
	ret0, _ := ret[0].(*pb.PostProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostProduct indicates an expected call of PostProduct.
func (mr *MockCatalogServiceClientMockRecorder) PostProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostProduct", reflect.TypeOf((*MockCatalogServiceClient)(nil).PostProduct), varargs...)
}
