// Code generated by MockGen. DO NOT EDIT.
// Source: account/service.go
//
// Generated by this command:
//
//	mockgen -source=account/service.go -destination=account/service_mock.go -package=account
//

// Package account is a generated GoMock package.
package account

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAccount mocks base method.
func (m *MockService) GetAccount(ctx context.Context, id string) (*Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	ret0, _ := ret[0].(*Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockServiceMockRecorder) GetAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockService)(nil).GetAccount), ctx, id)
}

// GetAccounts mocks base method.
func (m *MockService) GetAccounts(ctx context.Context, skip, take uint64) ([]Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx, skip, take)
	ret0, _ := ret[0].([]Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MockServiceMockRecorder) GetAccounts(ctx, skip, take any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockService)(nil).GetAccounts), ctx, skip, take)
}

// PostAccount mocks base method.
func (m *MockService) PostAccount(ctx context.Context, name string) (*Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostAccount", ctx, name)
	ret0, _ := ret[0].(*Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostAccount indicates an expected call of PostAccount.
func (mr *MockServiceMockRecorder) PostAccount(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostAccount", reflect.TypeOf((*MockService)(nil).PostAccount), ctx, name)
}
